# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 主题重新定义配置文件 V2
# 作者：EVANNOTFOUND
# GitHub地址：https://github.com/EvanNotFound/hexo-theme-redefine
# 文档地址：https://redefine-docs.ohevan.com
# 演示地址：https://redefine.ohevan.com
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# BASIC INFORMATION >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 基本信息
info:
  # 网站标题
  title: Pu Dianheng's blog
  # 作者名称
  author: ELecmark
  # 网站URL
  url: https://elecmark.github.io/
# BASIC INFORMATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# IMAGE CONFIGURATION >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 图片配置
defaults:
  # 网站图标
  favicon: /images/pdh-logo.webp
  # 网站logo
  logo: /images/pdh-logo.webp
  # 网站头像
  avatar: /images/pdh-logo.webp
# IMAGE CONFIGURATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# COLORS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 颜色配置
colors:
  # 主要颜色
  primary: "#A31F34"
  # 次要颜色（测试版）
  secondary: 
# COLORS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# SITE CUSTOMIZATION >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 网站定制
global:
  # 自定义字体
  fonts:
    # 中文字体
    chinese: 
      enable: true # 是否启用自定义中文字体
      family:  # 字体系列
      url:  # 字体URL到CSS文件
    # 英文字体
    english: 
      enable: true # 是否启用自定义中文字体
      family:  # 字体系列
      url:  # 字体URL到CSS文件
  # 内容最大宽度
  content_max_width: 1000px
  # 侧边栏宽度
  sidebar_width: 210px
  # 鼠标悬停效果
  hover:
    shadow: true # 阴影效果
    scale: false # 缩放效果
  # 滚动进度
  scroll_progress:
    bar: true # 进度条
    percentage: true # 百分比
  # 网站计数器
  website_counter:
    url: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js # 计数器API URL（无需更改）
    enable: true # 是否启用网站计数器
    site_pv: true # 网站页面浏览量
    site_uv: true # 网站独立访客数
    post_pv: true # 文章页面浏览量
  # 是否启用单页面体验（使用swup）。 参见 https://swup.js.org/。 类似于pjax
  single_page: true
  # 是否启用开放图形
  open_graph: true
  # 谷歌分析
  google_analytics:
    enable: false # 是否启用Google Analytics
    id:  # Google Analytics测量ID
# SITE CUSTOMIZATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end
    

# FONTAWESOME >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 图标库
fontawesome: # Pro v6.2.1
  # Thin version
  thin: false
  # Light version
  light: false
  # Duotone version
  duotone: false
  # Sharp Solid version
  sharp_solid: false
# FONTAWESOME <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# HOME BANNER >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 主页横幅
home_banner:
  # 是否启用主页横幅
  enable: true
  # 主页横幅样式
  style: fixed # 静态或固定
  # 主页横幅图像
  image: 
    light: /images/wallhaven-wqery6-light.webp # 亮色模式
    dark: /images/wallhaven-wqery6-dark.webp # 暗色模式
  # 主页横幅标题
  title: Elecmark-Pu Dianheng
  # 主页横幅副标题
  subtitle:
    text: ["“Life is a bug, and you are the programmer.”",
          "“Nothing is true, everything is permitted.” ——「刺客信条」",
          "“Life endures, birth continue.” ——「艾尔登法环」",
          "“Open your eyes.” —— 「塞尔达传说：荒野之息」",
          "“直面天命。” —— 「黑神话：悟空」"
          ] # 副标题文本，数组
    hitokoto:  # 一言配置
      enable: false # 是否启用一言
      api: https://v1.hitokoto.cn?c=c #（?c=b&c=c请求获得一个分类是漫画或游戏的句子） # API URL，可以添加类型，参见 https://developer.hitokoto.cn/sentence/#%E5%8F%A5%E5%AD%90%E7%B1%BB%E5%9E%8B-%E5%8F%82%E6%95%B0

    typing_speed: 50 # 打字速度（毫秒）
    backing_speed: 30 # 撤销速度（毫秒）
    starting_delay: 100 # 开始延迟（毫秒）
    backing_delay: 5000 # 撤销延迟（毫秒）
    loop: true # 是否循环
    smart_backspace: true # 是否智能退格
  # 主页横幅文本颜色
  text_color: 
    light: "#fff" # 亮色模式
    dark: "#d1d1b6" # 暗色模式
  # 文本的特定样式
  text_style: 
    # 标题字体大小
    title_size: 2.8rem
    # 副标题字体大小
    subtitle_size: 1.5rem
    # 标题和副标题之间的行高
    line_height: 1.2
  # 主页横幅自定义字体
  custom_font: 
    # 是否启用自定义字体
    enable: false
    # 字体系列
    family: 
    # 字体CSS文件的URL
    url:
  # 主页横幅社交链接
  social_links:
    # 是否启用
    enable: true
    # 社交链接
    links:
      github:  https://github.com/Elecmark
      email:  944723112@qq.com
      fa-solid fa-c fa-fw fa-lg: https://blog.csdn.net/LanLinHui?type=blog # CSDN
      steam: https://steamcommunity.com/profiles/76561198167581914/
      instagram: # 你的Instagram URL
      zhihu:  # 你的知乎 URL
      twitter:  # 你的twitter URL

      # ...... # 你可以添加更多链接
    # 带有二维码抽屉的社交链接
    qrs:
      weixin:  # 你的微信二维码图片URL
      # ...... # 你可以添加更多
# HOME BANNER <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# NAVIGATION BAR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 导航栏
navbar:
  # 自动隐藏导航栏
  auto_hide: false
  # 导航栏背景颜色
  color:
    left: "#f78736" # 左侧 
    right: "#367df7"  # 右侧
    transparency: 25 # 百分比（10-99）
  # 导航栏链接
  links:
    Home: 
      path: / 
      icon: fa-regular fa-house # 可为空
    作品集Portfolio: 
      path: /tags/作品集/
      icon: fa-regular fa-archive # 可为空
    关于About: 
      icon: fa-regular fa-user
      submenus:
        我的信息Me: /about
        友链Friends: /links
        时间轴Timeline: /archives
        #Github: https://github.com/EvanNotFound/hexo-theme-redefine
        #Blog: https://ohevan.com
        #Friends: /friends
  # 导航栏搜索（本地搜索）。需要hexo-generator-searchdb（npm i hexo-generator-searchdb）。参见 https://github.com/theme-next/hexo-generator-searchdb
  search:
    # 是否启用
    enable: true
    # 在页面加载时预加载搜索数据
    preload: true
# NAVIGATION BAR <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# HOME PAGE ARTICLE SETTINGS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 主页文章设置
home:
  # 侧边栏设置
  sidebar:
    enable: true # 是否启用侧边栏
    position: left # 侧边栏位置。左，右
    first_item: menu # 侧边栏中的第一个项目。菜单，信息
    announcement: # 公告文本
    links:
      时间轴Timeline: 
        path: /archives 
        icon: fa-solid fa-timeline # 可为空
      标签Tags: 
        path: /tags 
        icon: fa-regular fa-tags # 可为空
      分类Categories: 
        path: /categories 
        icon: fa-regular fa-folder # 可为空
  # 文章日期格式
  article_date_format: auto # 自动，相对，YYYY-MM-DD，YYYY-MM-DD HH:mm:ss等
  # 文章类别可见性
  categories:
    enable: true  # 是否启用
    limit: 5 # 最多显示的类别数
  # 文章标签可见性
  tags:
    enable: true  # 是否启用
    limit: 3  # 最多显示的标签数
# HOME PAGE ARTICLE SETTINGS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# ARTICLE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文章设置
articles:
  # 设置文章的样式
  style:
    font_size: 16px # 字体大小
    line_height: 1.5 # 行高
    image_border_radius: 14px # 图像边框半径
    image_alignment: center # 图像对齐方式。左，中
    image_caption: false # 是否显示图像标题
    link_icon: true # 是否显示链接图标
  # 字数统计。需要hexo-wordcount（npm install hexo-wordcount）。参见 https://github.com/willin/hexo-wordcount
  word_count:
    enable: true # 是否启用
    count: true # 是否显示字数统计
    min2read: true # 是否显示阅读时间
  # 作者标签
  author_label: 
    enable: true # 是否启用
    auto: false # 是否自动添加作者标签，例如Lv1，Lv2，Lv3...
    list: [VIP]
  # 代码块设置
  code_block:
    copy: true # 是否启用代码块复制按钮
    style: mac # mac | simple
    font: # 自定义字体
      enable: false # 是否启用
      family: # 字体系列
      url: # 字体URL到CSS文件
  # 目录设置
  toc:
    enable: true # 是否启用目录
    max_depth: 3 # 目录深度
    number: false # 是否自动为目录添加编号
    expand: true # 是否展开目录
    init_open: true # 默认打开目录
  # 是否启用版权声明
  copyright: true
  # 是否启用图像的懒加载
  lazyload: true
  # 文章推荐。需要nodejieba（npm install nodejieba）。从hexo-theme-volantis移植。
  recommendation:
    # 是否启用文章推荐
    enable: false
    # 文章推荐标题
    title: 推荐阅读
    # 显示的最大文章数
    limit: 3
    # 移动端显示的最大文章数
    mobile_limit: 2
    # 占位图像
    placeholder: /images/wallhaven-wqery6-light.webp
    # 跳过目录
    skip_dirs: []
# ARTICLE <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# COMMENT >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 评论设置
comment:
  # 是否启用评论
  enable: true
  # 评论系统
  system: waline # waline, gitalk, twikoo, giscus
  # 系统配置
  config:
    # Waline评论系统。参见 https://waline.js.org/
    waline:
      serverUrl: https://example.example.com # Waline服务器URL。例如 https://example.example.com
      lang: zh-CN # Waline语言。例如 zh-CN，en-US。参见 https://waline.js.org/guide/client/i18n.html
    # Gitalk评论系统。参见 https://github.com/gitalk/gitalk
    gitalk:
      clientID: # GitHub应用程序客户端ID
      clientSecret: # GitHub应用程序客户端密钥
      repo: # GitHub存储库
      owner: # GitHub存储库所有者
    # Twikoo评论系统。参见 https://twikoo.js.org/
    twikoo:
      version: 1.6.10 # Twikoo版本，如果不知道是什么，则不要修改
      server_url: # Twikoo服务器URL。例如 https://example.example.com
      region: # Twikoo地区。可以为空
    # Giscus评论系统。参见 https://giscus.app/
    giscus:
      repo: # Github存储库名称 例如 EvanNotFound/hexo-theme-redefine
      repo_id: # Github存储库ID
      category: # Github讨论类别
      category_id: # Github讨论类别ID
      mapping: pathname # 用作页面唯一标识符的哪个值。例如 pathname，url，title，og:title。由于pjax不会在页面更改时更新og:title，因此不要使用og:title
      strict: 0 # 是否启用严格模式。例如 0, 1
      reactions_enabled: 1 # 是否启用反应。例如 0, 1
      emit_metadata: 0 # 是否发出元数据。例如 0, 1
      lang: en # Giscus语言。例如 en，zh-CN，zh-TW
      input_position: bottom # 将评论框放置在评论之上/之下。例如 top, bottom
      loading: lazy # 懒加载评论
# COMMENT <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# FOOTER >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 页脚
footer:
  # 显示网站运行时间
  runtime: true # 是否显示网站运行时间
  # 页脚图标，在此处编写fontawesome图标代码
  icon: '<i class="fa-solid fa-heart fa-beat" style="--fa-animation-duration: 0.5s; color: #f54545"></i>'
  # 网站启动时间，格式：YYYY/MM/DD HH:mm:ss
  start: 2023/9/24 19:02:20
  # 页脚消息
  customize:
  # ICP备案号。参见 https://beian.miit.gov.cn/
  icp:
    enable: false # 是否启用
    number: # ICP备案号
    url: # ICP备案URL
# FOOTER <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# INJECT >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 注入
inject:
  # 是否启用注入
  enable: false
  # 注入自定义头部HTML代码
  head: 
    -
    -
  # 注入自定义页脚HTML代码
  footer:
    -
    -
# INJECT <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end



# PLUGINS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 插件
plugins:
  # RSS订阅。需要hexo-generator-feed（npm i hexo-generator-feed）。参见 https://github.com/hexojs/hexo-generator-feed
  feed:
    enable: false # 是否启用
  # Aplayer。参见 https://github.com/DIYgod/APlayer
  aplayer:
    enable: true # 是否启用
    type: fixed # fixed, mini
    audios:
      - name: 纯音乐
        artist: Guitar
        url: /music/校园吉他纯音乐.mp3
        cover: /music/covers/music.svg
#      - name: # 音频名称
#        artist: # 音频艺术家
#        url: # 音频URL
#        cover: # 音频封面URL
      # .... 你可以在这里添加更多音频
  # Mermaid JS。需要hexo-filter-mermaid-diagrams（npm i hexo-filter-mermaid-diagrams）。参见 https://mermaid.js.org/
  mermaid:
    enable: false # 是否启用
    version: "9.3.0" # 默认v9.3.0
# PLUGINS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# PAGE TEMPLATES >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
page_templates:
  # Friend Links page column number
  friends_column: 2
  # Tags page style
  tags_style: blur # blur, cloud
# PAGE TEMPLATES <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end


# CDN >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
cdn:
  # Whether to enable CDN
  enable: false
  # CDN Provider
  provider: jsdelivr # jsdelivr, unpkg, aliyun, custom
  # Custom CDN URL
  # format example: https://cdn.custom.com/hexo-theme-redefine/${version}/source/${path}
  # The ${path} must be in the source folder of the theme
  custom_url: 
# CDN <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# DEVELOPER MODE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
developer:
  # Whether to enable developer mode (only for developers who want to modify the theme source code, not for ordinary users)
  enable: false
# DEVELOPER MODE <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end